version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: rcryptocurrency_db
    restart: always
    environment:
      POSTGRES_USER: rcc_user
      POSTGRES_PASSWORD: rcc_password
      POSTGRES_DB: rcc_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
